// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, fs, http, io, mime, multiparty, server, util;

  express = require("express");

  http = require("http");

  app = express();

  server = http.createServer(app);

  io = require("socket.io")(server);

  util = require("util");

  mime = require("mime");

  fs = require("fs");

  multiparty = require("multiparty");

  app.use(express["static"]("public"));

  app.get("/", function(req, res) {
    return res.render("index.jade", {
      title: "My Site"
    });
  });

  app.post("/", function(req, res) {
    var form;
    form = new multiparty.Form();
    return form.parse(req, function(err, fieldsObject, filesObject, fieldsList, filesList) {
      var img, path;
      img = filesObject;
      path = img['uploaded'][0].path;
      return fs.readFile(path, function(err, buf) {
        var data;
        if (err != null) {
          res.status(422);
          return;
        }
        data = buf.toString("base64");
        io.sockets.emit("push_image", {
          dataUrl: util.format("data:%s;base64,%s", mime.lookup(path), data)
        });
        return res.end();
      });
    });
  });

  server.listen(PORT, HOST);

}).call(this);
