// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, express, fs, http, io, server;

  express = require("express");

  http = require("http");

  app = express();

  server = http.createServer(app);

  io = require("socket.io")(server);

  fs = require("fs");

  app.use(express["static"]("public"));

  bodyParser = require('body-parser');

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.get("/", function(req, res) {
    return res.render("index.jade", {
      title: "My Site"
    });
  });

  app.post("/", function(req, res) {
    console.log(req.params);
    return res.send("accepted");
  });

  server.listen(3000);

}).call(this);
