// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, fs, http, io, mime, multiparty, server, util;

  express = require("express");

  http = require("http");

  app = express();

  server = http.createServer(app);

  io = require("socket.io")(server);

  util = require("util");

  mime = require("mime");

  fs = require("fs");

  multiparty = require("multiparty");

  app.use(express["static"]("public"));

  app.get("/", function(req, res) {
    return res.render("index.jade", {
      title: "My Site"
    });
  });

  app.post("/", function(req, res) {
    return io.sockets.emit("update", req.body);
  });

  server.listen(process.env.PORT);

}).call(this);
