// Generated by CoffeeScript 1.10.0
(function() {
  var socket;

  socket = io.connect('http://localhost:8080');

  socket.on("push_image", function(data) {
    $('<img style="display: block;">').attr('src', data.dataUrl).prependTo($("body"));
  });

}).call(this);
