// Generated by CoffeeScript 1.10.0
(function() {
  var socket;

  socket = io.connect(location.href);

  socket.on("push_image", function(data) {
    $('img').fadeOut();
    $('<img style="display: block;">').attr('src', data.dataUrl).fadeIn();
  });

}).call(this);
